sudo: false
language: python
python:
    - "3.6"
    - "2.7"
addons:
    postgresql: "9.6"
services:
    - postgresql
branches:
    only:
        - master
env:
    global:
        - SECRET_KEY=SecretKeyForTravis
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
install:
    - sudo apt-get install -y postgresql-9.6-postgis-2.3
    - psql -U postgres -c "create extension if not exists postgis"
    - pip install pip --upgrade
    - pip --version
    - pip install -r requirements.txt
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - python manage.py migrate --noinput
script:
    - python manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "ap-southeast-2"
  app: "eb-biosys"
  env: "eb-biosys-uat"
  bucket_name: "elasticbeanstalk-ap-southeast-2-501507701749"
  on:
    branch: uat
